name: CI/CD Workflow For case service

on:
  push:
    paths:
      - hospital-management/case-service/**
      
jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'
        
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: GitLeaks Scan
      run: |
        cd hospital-management/case-service
        ls -ltr
        docker pull abhijeetnirphal/gitleaks
        git fetch --unshallow
        docker run -v "$(pwd):/path" abhijeetnirphal/gitleaks     

    - name: Run Unit Tests
      run: |
        cd hospital-management/case-service
        mvn test
          
    - name: Perform Google Formatter Check
      run: |
        cd hospital-management/case-service
        mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: OSS scan
      run: |
       cd hospital-management/case-service
       mvn ossindex:audit
      continue-on-error: true


    - name: OWASP scan
      run: |
        cd hospital-management/case-service
      if: false
       mvn org.owasp:dependency-check-maven:check


    - name: Build code and create docker images
      run: |
       cd hospital-management/case-service
       mvn clean install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME
         

    - name: License finder
      run: |
       cd hospital-management/case-service
       docker pull abhijeetnirphal/license-finder:latest
       docker run -v "$(pwd):/scan" abhijeetnirphal/license-finder:latest
  

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push docker images
      run: |
        cd hospital-management/case-service
        CURRENT_FOLDER_NAME=$(basename $(pwd))
        docker push ${{vars.DOCKER_REGISTRY_USER}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME 
          
