name: CI/CD Workflow

on:
  push:
    branches:
      - main

env: 
  DIRS: "api-gateway patient-service directory-service case-service appointment-service"

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: License finder
      run: |
        for dir in ${{env.DIRS}}
        do
          cd hospital-management/$dir
          docker pull abhijeetnirphal/license-finder:latest
          echo "Scanning directory: $(pwd)"
          ls -ltr
          mvn clean
          docker run -v "$(pwd):/scan" abhijeetnirphal/license-finder:latest 
          cd -
        done
    - name: GitLeaks Scan
      run: |
        for dir in ${{ env.DIRS }}
        do
          cd hospital-management/$dir
          docker pull abhijeetnirphal/gitleaks
          docker run -v "$dir:/path" abhijeetnirphal/gitleaks
          cd -
        done

    - name: Perform Google Formatter Check
      run: |
        for dir in ${{ env.DIRS }};
        do
          cd hospital-management/$dir
          mvn com.spotify.fmt:fmt-maven-plugin:check
          cd -
        done

    - name: OSS scan
      run: |
        for dir in ${{ env.DIRS }};
        do
          cd hospital-management/$dir
          mvn ossindex:audit || true
          cd -
        done

    - name: OWASP scan
      run: |
        for dir in ${{ env.DIRS }}
        do
          cd hospital-management/$dir
          # mvn org.owasp:dependency-check-maven:check
          cd -
        done

    - name: Build code and create docker images
      run: |
        for dir in ${{ env.DIRS }}
        do
          cd hospital-management/$dir
          mvn clean install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME
          cd -
        done

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push docker images
      run: |
        for dir in ${{ env.DIRS }}
        do
          cd hospital-management/$dir
          CURRENT_FOLDER_NAME=$(basename $(pwd))
          docker push ${{vars.DOCKER_REGISTRY_USER}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME 
          cd -
        done


      


    

    
